In [1]:
import pandas as pd
from glob import glob

# using glob method to select all files from a bath

In [11]:
all_monthes = sorted(glob(r'C:\Users\Options\Desktop\SalesAnalysis\Sales_Data\Sales_*_*.csv'))
all_monthes

['C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_April_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_August_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_December_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_February_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_January_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_July_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_June_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_March_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_May_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_November_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_October_2019.csv',
 'C:\\Users\\Options\\Desktop\\SalesAnalysis\\Sales_Data\\Sales_September_2019.csv']

# concat all files in one variable

In [15]:
all_months_data =pd.concat((pd.read_csv(file).assign(filename = file)
        for file in all_monthes) ,ignore_index = True)

In [14]:
all_months_data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,filename
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
1,NaN,NaN,NaN,NaN,NaN,NaN,C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",C:\Users\Options\Desktop\SalesAnalysis\Sales_D...